import { Container, Row } from 'reactstrap'
import MilanSignature from '../app/assets/img/MilanSignature.png'

const AboutUsPage = () => {
    return (
        <Container>
            <Row>
                <h3>Where do we start?</h3>
                <p>"Life Coaching" can mean so many things to so many different people. And there is no shortage of people who will tell you they have it all figured out and try to sell you the answers. I don't and I won't. But I genuinly believe that I can help people find their own truth and create small, meaningful changes that have the power to alter their course in unimaginable ways.</p>
                <p>Below you will find my response to some of the questions to may be asking yourself. It isn't a short read, so "summary" would be a misnomer, but it is broken up into sections that are more easily digestable. Feel free to hop around and see what peaks your interest or, more importantly, what inspires you to ask MORE questions!</p>
                <p>If you find yourself connecting to the words, or wanting to dig deeper into anything that's resonated, please use the "Free Consultation" button at the top of the page to reach out. I would love to hear from you.</p>
                <p>Kindest regards,</p>
                <span>
                    <img src={MilanSignature} alt="Milan Signature"  />
                </span>
            </Row>
            <Row>
                <h3 className="mt-5">Black Point. Life Navigation.</h3>
                    <p><strong>Life Navigation</strong>, to me, is more of a true representation of what I do than life coaching. Yes, by most people’s definition I am a life coach. Unfortunately, those two words might have a bit of bad rep to them, with life coaching services and apps all over the web, some promising to “coach” you (in other words, tell you what to do) into happiness ever after. I don’t want to coach you into anything, that would presume that I know what is best for you and I don’t. Chances are that neither do you at the moment, and that is why you landed on this website. I can help you find it and help you set your “black point” but I will not be telling you what value of black point is ‘best’ for you, that is for you to decide. After all, you may like your photographs looking differently than I like mine, and that is absolutely fine. So, I will not coach as much as I will help you navigate. Like the navigation app on your phone or that smart computer in your car – I will first need to know where you are right now, you’ll tell me where it is you want to go, let me know your preferences (do you like the shortest or the most scenic route, are you ok with congestion or do you prefer roads less traveled?), and I will suggest ways to get there. There may be faster and wider highways where you save time, although there may be tolls, and there are slower winding mountain roads with pot holes, and perhaps beautiful views. Which one you take is up to you. In short, <strong><em>coaching</em></strong> implies you do what I tell you to do, not unlike an athlete who follows his or her coach’s training plan to achieve results, whereas <strong><em>navigation</em></strong> implies that I suggest possible routes to your chosen destination while you remain in charge of making a decision. And as far as what you do with your life, you, and only you will always be in charge of that.</p>
                <h3 className="mt-5">Prerequisites to a Successful Life Navigation Relationship</h3>
                    <p>As any human interaction, a life coaching/life navigation relationship is a two-way street. Both you and I need to actively participate. If anyone tells you they have solutions for your life’s challenges and all you need to do is sit there, listen and take notes, they’re either straight up lying to you or very mistaken in their beliefs of what they can and cannot do. Frankly, most of the actual doing will be done by you. You may or may not be ready to assume a more active part in your life and total responsibility for it, but when you are, it won’t happen with you watching from the stands, you will need to get dirty on the field with the rest of the team – yes, that would be me. There are a few things that will help us work as a team and I will briefly mention them here.</p>
                    <h6><strong>MUTUAL TRUST</strong></h6>
                        <p>If we don’t trust each other, we won’t get very far. If you don’t trust that I have your best interest in mind and the skills to help you, and I don’t trust that you have the desire and willingness to change and work on yourself, we will only be wasting my time and your money. Yes, it typically takes time to gain trust (while it, ironically, only takes a moment to loose it), but let’s both do our absolute best to be able to build trust with each other. </p>
                        <p id="italic">“I am not upset because you lied to me, I am upset because from this moment on I won’t be able to trust you” (Sigmund Freud, supposedly)</p>
                    <h6><strong>HONESTY</strong></h6>
                        <p>Honesty goes hand in hand with trust. If you believe that I’m an honest person, you’ll probably find it a lot easier to trust me. If, on the other hand, I’ve shown you that I am a dishonest person it would be foolish of you to trust me at all. If you’re not honest with me, there will be a lot of guesswork involved in my efforts to help you. If I lied to you, withheld information or manipulated  my observations, I’d be making it impossible for you to direct your focus where it needs to go. </p>
                        <p>The hardest part about honesty is being <strong><em>honest with yourself</em></strong>. Most of us (myself included) find it a lot easier to be honest with other people than ourselves. Being honest with ourselves requires a hard look inside and willingness to feel a little (or very, depending) discomforted by what we see. To make any meaningful progress in life, being honest with yourself is a necessary first step on a path to improvement.</p>
                    <h6><strong>YOUR DESIRE TO CHANGE MUST BE GREATER THAN YOUR DESIRE TO REMAIN THE SAME</strong></h6>
                        <p>It sounds very simple, doesn’t it? Most profound truths do. If our desire to change is not greater than our desire to stay where we are, we don’t move, we don’t change. If we feel comfortable where we are right now, nobody can give us a good enough reason to become uncomfortable and make effort to get off the couch and go to a place we may or may not like, instead of remaining in a place/state we know <strong><em>and</em></strong> like – unless, of course, we’re masochists or adrenaline junkies. With a bit of a stretch, one of Newton’s laws could be applied here: ‘we remain in motion or in a motionless state, unless forced into a change by an outside force.’ Except in the case of a change of direction in life, that force often comes from <strong><em>inside</em></strong> of us, our own will and decision. The outside force would be life itself, and although not formulated by Newton, I do believe it to be a universal law of a sort – if we don’t pay attention and don’t initiate necessary changes to our life from within, life itself will kick start that initiation for us, although it is typically way more painful than the change voluntarily initiated from within. In fact, that is why and how most of us arrive at the conclusion that our life needs a recalibration, because we have  been painfully and forcefully reminded by life itself that something is out of whack. That ‘kick in the butt’ is usually enough for us to start noticing. When it isn’t, we get another, more powerful one later. And yes, that cycle goes on and on and on.., until we finally stop, take a breath, start paying attention and actively begin the act of rebalancing our lives. </p>
                        <h6><strong>ACCOUNTABILITY</strong></h6>
                        <p>I will hold you accountable for your words and actions and I want you to hold me accountable for my words and actions. I take full responsibility for my words and actions and I want you to do the same. I will hold myself accountable and I would like you to hold yourself accountable. Nothing you do or say is someone else’s fault, own it.</p>
                    <h6><strong>CLEAR COMMUNICATION</strong></h6>
                        <p>Communication can be tricky. People communicate with each other both verbally and non-verbally. Verbal communication is what we are saying to each other, words and sentences. Non-verbal communication would include tone of voice, gestures, body language, demeanor.. </p>
                        <p>The pitfall of verbal communication is meaning. The meaning that the person speaking assigns to the words and sentences spoken, and the meaning the person listening assigns to the same words and sentences. Unfortunately, that meaning is not always the same to each of the participants of a conversation. I strongly believe, that I am responsible for what I said, not for what you heard. However, that being said, it is a good idea (and there’s a good chance I will do that often during our conversations) to clarify and ask additional questions if there’s any doubt at all that perhaps I did not hear what you said the way you meant it and I would encourage you to do the same. I know it sounds very trivial and obvious, but most of us are not nearly as good communicators as we’d like to believe. As impractical as this might be to do every time we’re in a conversation with another person, some kind of a short version of asking the following four questions when we’re not sure whether we really heard what someone else was trying to say would be helpful. Those questions are: 1. What did he/she want to say? 2. What did he/she actually say? 3. What did I hear him/her say? 4. What do I think does what he/she said mean?</p>
                <h3 className="mt-5">Black Point Priciples & Philosophies</h3>
                    <p>There are quite a few approaches to life coaching/life navigation, and while I’m willing to assume that all of them work to some degree, I will say that not all of them work for everyone. Neither does mine. Will it work for you? That is the first important question you will need to answer for yourself. I will never make you a promise I can’t keep, and, starting right here, I am not claiming that my approach is best suited for your life journey or that it will make all of your life’s challenges disappear, no matter how hard you’re willing to work at it. What I am suggesting is that you keep reading, see what principles and values my coaching approach is based on, and if what you see resonates with your core values and beliefs about life, then my coaching sessions might be a good fit for you and I’ll be honored to help you navigate on your journey through life. A promise I am making to you, and one that I will keep, is that I will do my absolute best to find a way to rebalance your life that works for you. If, on the other hand, what I’m saying sounds like a bunch of crap to you, perhaps you need to keep looking and find someone who’s methods and philosophies are closer to your personal outlook on life. If you keep your eyes open, that right person will show up eventually, even if it’s not me, here and now.</p>
                    <h6><strong>BALANCE AND CHANGE</strong></h6>
                        <p>If I could only use one word to express what I believe is important in life, that word would be <strong><em>balance</em></strong>. Happiness, that elusive feeling we all believe to be striving for depends largely on balance. When we feel that our life is well balanced, even keeled, anchored, we can take on anything while retaining the feeling of general happiness. When we’re unbalanced, out of whack, ‘undone’, any small and seemingly insignificant event can tip us over the edge or become the proverbial last drop. Happiness is lost, and, at best, only temporarily regained for brief periods of time during favorable life events or moments. </p>
                        <p>Balance is a funny thing, though. More often than not – balance is somewhat unstable and fragile. Why? The short answer would be: physics and human nature. it is unstable, because, once achieved, it only lasts as long as <strong><em>nothing changes</em></strong>. In life, changes happen all the time, and are not only unavoidable but often desirable. Births, deaths, physical and mental health, marriages, living situation, getting hired and fired, change of seasons, aging, geopolitical situation, social changes and shifts.. we could keep going for pages and pages to list all the changes that <strong><em>will</em></strong> happen to (or, at the least, around) most of us throughout our lives whether we like it or not. Change is unavoidable, it will happen with or without any of our doing or non doing, the world around us as well as the world within us will change and nobody will ask us if we’re ok with it or ready for it. So how do we keep balance in our lives when we have very little control over the changing nature of life (although we’re the masters of convincing ourselves that most of what happens in life happens under our control)? We adjust to the changes around and within us. Often. The ability to make those, sometimes subtle and other times major, adjustments could easily be one of the most important metrics and skills by which we measure the self-perceived ‘success’ in life. Those of us that learn to adjust <strong><em>timely</em></strong> and <strong><em>proportionately</em></strong> end up being happier with the way life goes. Those that don’t, end up being constantly caught by surprise and chasing their own tail, being disillusioned and disappointed by life events. Some of us do adjust often, but are not very good at gauging how much adjustment is needed.  Some don’t adjust enough, and become feeling hopeless and defeated, feeling like our efforts are futile. Some of us overcorrect, overadjust when faced with a need for adjustment, ending up even more out of balance, although perhaps in the opposite direction. Yes, the art of life balance is a bit like winter driving. When your car starts skidding on ice, don’t correct at all or correct too little and you’ll end up in a ditch, correct too much and you’ll also end up in the ditch. Let off the gas pedal, stay calm, present, and concentrate on the wheel and the road, and you will most likely come out of the skid just fine.  </p>
                        <p>Balance will be an important part of initiating any life or lifestyle changes. As an example (blown out of proportion and exaggerated for effect and demonstration purposes), if you decide that you want to be in a great physical shape and start spending 8 hours a week in a gym, run a half-marathon every other Saturday and start getting up at 6 every morning to swim 30 laps at the pool, how will that affect other areas of your life? Will your relationship, work, sleep schedule, your personal improvement in other than physical areas suffer in any way? And if any of those areas do suffer because of the change you implemented, are you ok with that? Are you willing to give up some of your time and focus previously dedicated to other areas of life for this change? If the answer is yes, then you’re ready for the next step and the next question – how exactly do I go about implementing that change and what exactly am I willing to give up elsewhere? (even if what you’re giving up is just sitting on your couch and watching TV). How do you recalibrate and rebalance timely and proportionately..</p>
                    <h6><strong>SURRENDERING TO THE FLOW</strong></h6>
                        <p>This principle took me years to understand and appreciate, and, I admit, is one that sounds very counter-intuitive to a vast majority of us the first, second, and perhaps even the fiftieth time we contemplate the meaning of it. Here is where I share a very personal, and at the time quite painful, experience from my own life tumbles. </p>
                        <p>Six years ago, I divorced my wife of ten years and allowed (and participated in) breaking apart a family of 4 with two very young children. In the last couple years leading up to our divorce, my wife was cheating on me, started behaving in ways I did not understand, and, from my perspective, turned into a person I have never met before. I spent months trying to understand what was happening to her, us, suggested marriage counseling after months of unsuccessful efforts to reconcile, spent countless hours on the internet researching sudden shifts in one’s personality, studying everything from side effects of birth control to hereditary predisposition to a mental breakdown, took a very hard and unpleasant look at myself and my possible contributions to the unfortunate and confusing place we found ourselves in, nothing was making any sense. Until one day, when I started paying attention to three letters that kept popping up during my google searches for ‘sudden shifts in personality and behavior’, the letters M, L and C. Midlife crisis. All that midlife crisis meant to me up to that point were amusing stories about family men in their fifties suddenly buying a Harley Davidson bike, joining a local rock band and getting a fresh tattoo on their shoulder.. What I started to learn was that MLC is a condition causing a total disintegration of one’s personality, is believed to be untreatable by traditional or non-traditional medicine, or psychotherapy, and may end by re-integration (although that isn’t always the case) anywhere between 2 and 20 years later, with the average being around 5. Before I continue, please understand that I am not, by any means, casting a diagnosis regarding my ex-wife’s mental state at the time, I am not a psychiatrist or otherwise qualified to diagnose anyone with any kind of personality disorder. I am simply sharing parts of my personal journey, from my subjective perspective, to illustrate a point..</p>
                        <p>All of the reading about MLC I dove into shed a lot of light on our situation and I finally had a feeling like I might be beginning to understand what was happening to us. That was the good news. You can’t fight something you don’t understand, and yes, I wanted to fight. My next question was: ‘If my wife is going through MLC, what can I do to help her?’ Here came the bad news. Nothing. There is, according to people who spent better parts of their adult life researching MLC absolutely nothing you can do for a loved one who is going through MLC, there isn’t even much that they themselves can do.. This is when I learned the catchy (unfortunately, in this case very true) phrase, the only way out is through. You leave them to it, and you either stand by, arm yourself with limitless patience and willingness to be subjected to their shifting moods, emotional abuse and  total disregard for any human being except themselves (sometimes including themselves), or you remove yourself from the situation, let them fight their own battle and pray for their successful reintegration.</p>
                        <p>I was, and to a lesser degree now still am, a fixer. I wanted to fix things, make things better, find a better way. How could I just stand by and let my marriage and family disintegrate without making any effort to stop it? I did something that my ego and pride were not ok with at all (my ego and pride dictated that I can solve all my problems myself,without anyone’s help), I joined a MLC support group for LBS or ‘left behind spouses’ (another abbreviation that was not part of my vocabulary up till that point). Each Left Behind Spouse was, upon request, assigned a mentor, a more seasoned LBS (most of whom were still ‘left behind’ by their spouses at the time of their mentoring), who would help us newbies navigate through the turmoil and confusion of trying to support someone we love on their journey through MLC. This is it, I thought, now I’ll have someone more experienced on my side, someone who has found a way, who will help me find my way out of helplessness and  a solution - every problem has a solution, right? </p>
                        <p>Well, here is what I learned and a point I am trying to make by sharing this short version of part of my personal journey. Not every problem has a solution, not when you limit the range of possible solutions with  expectation as to what the solution will look like. My mentor was a very patient, kind and understanding person and to this day I am very much grateful for all his support. In all of his responses to my questions (looking back I feel like I was asking the same ones over and over, looking for a solution, a loophole, a secret door, a blueprint for what to do) right above his signature was his ‘tagline’ if you will. It read: <strong><em>Surrender to the Flow</em></strong>. Not at all what I wanted to read or hear. I had no idea why he would proclaim such thing. Surrender to the flow? Surrender to anything I will not, I am fighting for the future of my family here! Has he surrendered, because he was too weak? Has he just taken the easy way out and now he is manipulating me to do the same? Is he a coward who gave up on his family and now HE wants me to listen to his advice? I fought it, I fought him, and in him I fought myself in a way.. Fought hard for over a year and gave it my absolute best. </p>
                        <p>In the end, I surrendered to the flow. Dizzy and exhausted I took a deep breath and let the flow carry me to where it was going, kicking, screaming and fighting, the entire time, through and out. Through my personal purgatory to acceptance, forgiveness and peace.</p>
                        <p>Our instincts and desires dictate that we make every effort imaginable <strong><em>to be in charge of our life</em></strong>. Most life coaching techniques will try to accomplish just that, help you feel like you are in control of your life, which can be a very empowering feeling on its own, and empowerment should be the goal of every life coach. It is my goal to empower you. In my opinion, however, being in charge of your life is a promise that can not be delivered by anyone, only a temporary illusion of it can – until life itself throws us another curveball. Life itself is too large of a force to be controlled by any one human being, and the longer we keep lying to ourselves about being able to learn some kind of a ‘secret’ to control life and destiny itself, the more we prolong our disappointment, pain and suffering. What we <strong><em>can</em></strong>, on the other hand, <strong><em>control 100% of the time</em></strong>, is how we respond to life. I am going to repeat that: You will never be in total control of your life, but you can be in total control of how you respond to life. </p>
                        <p>That is what I learned (and the learning continues), and that is what I want to help you learn as well. That choice to take control of how we respond to life is, and will be, always ours and we get to choose as often and as many different responses/courses of action as we please. We can swim against the current and, if we’re strong enough, even achieve a temporary victory against the flow of life, but there is no technique to learn to be able to ‘out-swim’ the current of life indefinitely. Eventually, we will get tired –  our level of energy, skill and resolve is finite, although the amounts of it can and do vary person to person. We can also choose to let the current cary us (which it will most of the time even if we choose to swim against it, when we run, again and again, out of energy to fight it) and only make timely and proportionate adjustments to avoid large rocks and other obstacles in the river of life. That is way easier and totally achievable, since most of the energy required for that is provided by the current itself, not by our willpower and resolve, and if we learn a few simple moves and <strong><em>pay enough attention to the current</em></strong>, we can float with the flow indefinitely. Surrendering to the flow sounds passive, lazy, effortless. Feels like giving up. It is neither. Being continually aware and attentive to the flow of life requires active focus, continuous adjustment, perseverance and vigilance. It isn’t giving up, it is choosing action carefully and thoughtfully, in harmony with the force of life itself.  All it means is that we shift our focus and energy from fighting the forces of life to continually and consistently observing and learning them. </p>
                        <p>The concept of choosing the path of least resistance has been around for a very long time, and is the central idea of the teachings of Tao te Ching, relatively thin and small book that some people keep coming back to for guidance and wisdom in times of difficulties and others have been grossly oblivious to for their entire lives. </p>
                        <p>Surrendering to the flow, or surrendering to anything for that matter, is not a very popular concept in our fast-paced and self-centered culture. We like to conquer, win, take charge, defeat.. One of our secret wet dreams as a society is beating death, avoiding it, or at least somehow wrestling more time out of it, while countless generations of humans before us knew how to accept it, the same way they accepted life.  Surrendering to the flow is not an act of defeat. It is an act of acceptance. If you want to learn how to control life itself (yes, even your own), I can’t help you. If you want to learn how control you responses to life, then I can and will be honored to help you find you very own way of doing that.</p>
                    <h6><strong>ESTABLISHING WHAT WE REALLY WANT</strong></h6>
                        <p>Imagine you could get anything you want. Any one thing. What would it be?</p>
                        <p>Some version of the myth/story of a magical entity granting a human being three wishes probably exists in every culture on Earth. Remember how it usually ends? Either the poor man/woman wastes their three wishes on unimportant material stuff and in the end they end up exactly where they started, or they smarten up right after they wasted the first two and there is a happy ending. I don’t know a single version of that story where the person, suddenly faced with the opportunity to have <strong><em>any</em></strong> three wishes granted on the spot says: “Oh, great, I’ve been thinking about this a lot and this is what I want”. They get their three wishes granted (accompanied  by the necessary visual and sound effects), and live happily ever after. That version does not exist. <em>Why?</em></p>
                        <p>It may come as a surprise to you, as much as it did to me – most of us have no idea what it is we actually want. Some of us think we know what we want, until we actually get it, and it turns out to not be the thing we really wanted. Even one of the most acclaimed human psychology experts of the last century, Abraham Maslow acknowledges that knowing what we want is a lot harder task for most people than it may seem. So how do we get our three wishes granted if we don’t even know what they are?</p>
                        <p>Well, here’s the good and bad news again. Good news is, we are not limited to 3 or any other particular number of wishes per lifetime. We can wish to attain as much in life as we are willing to work toward (as long as we give up on the idea of having all of it and having it right now). The bad news, unless you happen to be a happy owner of a magical lantern, teacup or other vessel for a Genie, you’ll actually have to work for each and every one of them. And if you keep not knowing what you want and just keep working toward a goal after a goal, wish after a wish, only to realize that ‘this wasn’t it’..well let’s just say that’s a lot of working to do. The silver lining of that approach is that with all the practice you’ll probably get pretty good at ‘working toward it’.</p>
                        <p>Applying nothing but pure and simple logic, there seem to be three (there must be something about that number after all..)  basic options:</p>
                        <ol className="ms-5">
                            <li> Keep working toward one goal/wish at a time, perhaps we’ll eventually, even if accidentally, end up working toward and getting what we really want.</li>
                            <li>Want less, ideally nothing, and be happy with what we have already – then there’s nothing to figure out and nothing to work toward.</li>
                            <li>Give a hard, long thought to what it is we really want, think about why we want it, how it will improve our lives or life of someone else. If it is (likely the case for most of us) more than one thing, come up with an order of importance and start working at one at a time, starting with the most important/meaningful goal. If we end up with too many goals we want to work toward (also highly likely for most of us), prioritize and scratch the ones less important for the time being to not get overwhelmed and to keep our focus on what matters to us the most.</li>
                        </ol>
                        <p>Now, and this may be a good time for the first, although very brief, demonstration of how things are going to happen in a real one-on-one coaching/navigating session – I am not saying that any one option is the right answer for each and every one of us, although number 3 seems to be the logical conclusion of the narrative. I actually like 2 and 3 both, you may like 1, someone else might like 1 and 2. I am not telling you which option is best for you, that is for you to decide, I am just helping you see what your options are. And if you don’t like either one of them, then, unless we can uncover an additional  option to move forward, we won’t be making any headway until you choose. At this point (and that would be another choice for you to make), we can keep revisiting the topic until we find an answer or maintain status quo. Eventually, I probably won’t suggest another follow up session until a choice is made, because you’re either happy/satisfied where you are, or unwilling/unable to make a choose from options available to you and start working toward a goal, and you don’t need my help to stay where you are, you’ve done that just fine without me up till now.</p>
                        <p>But going back to establishing what we want. There are a few factors/questions that need to be considered/answered in that process.</p>
                        <ol className="ms-5">
                            <li>How is what I want going to improve my life or the life of someone else. If it isn’t, then why do I want it in the first place? We may think we want something, well, for a variety of reasons. Someone else is telling us (parents, partners, society as a whole..) that we should want it. Is that a good enough reason, to be ‘socially acceptable’, be ‘in’, please other people? In my opinion, no. Everybody else seems to want it. Again, no. What do other people’s priorities and desires have to do with mine? To want something because ‘everybody else’ wants it is a sign of mental laziness and refusal to make our own choices. Instead of going through the process of figuring out what we want, we let other people figure it out and just copy their choices/behavior. It will boost our ego and self-esteem. Once again – although perhaps less hard this time – no. It will help us live a more fulfilling and happier life, yes, absolutely worth wanting and working toward.</li><br />
                            <li>Understand, that what we want may, and most likely will, change over time. When we’re young, romantic relationships, social acceptance, and working toward future stability, for example, might be high on our scale of priorities. When we’re mature adults, steady, well paying and satisfying jobs as well as some level of recognition and status might creep up their way toward the top. When we’re old, health is most likely to be one of our top three priorities. Years ago I used to listen to this guy Sadhguru on youtube, who was all about enlightenment, elevating awareness and achieving miracles, he was/is a self-described mystic. In one interview, he was asked this question: “Sadhguru, is it really true that once you attain a certain level of awareness you can achieve anything you wish for?” And his answer was: “Yes it is true. But it is also very likely, that as you attain higher levels of awareness what you wish for will change”. </li>
                                <p><br />Our priorities and wishes change as we age, grow and mature (not necessarily at the same rate). Work toward what you really want now, but understand that no single goal will bring you everlasting happiness and fulfillment. What makes you happy and fulfills you now may not be the same thing that will make you happy and fulfill you in ten years.</p>
                            <li>Make sure that what you want and are willing to work toward aligns with your core values. Those are the values/principles you value above all else in life. Integrity, loyalty, strong family relationships, freedom, discipline, security.. those are just a very few examples of core values. If you want something that goes against your core values, there will be an inner conflict within you. Achieving it will not improve your life in any meaningful way. Certain core values will be part of most people’s mix (although the hierarchy will probably differ), others are very personal and different for each of us. No right or wrong here, our values are our values, but our goals do need to align with them to achieve any lasting satisfaction and happiness in life. If they don’t, the satisfaction and happiness will be very temporary at best, because sooner or later, consciously or unconsciously, we’ll start feeling that conflict, there will be some degree of perceived falseness about those goals  even when achieved. Establishing your personal core values will be part of one of our early sessions.</li>
                        </ol>
            </Row>
        </Container>
    )
}

export default AboutUsPage